name: Avenue Rouge Runway
pygments: true
markdown: rdiscount
authors:
  jennifer:
    name: Jennifer Palpallatoc
    display_name: Jennifer
    web: http://hauteofftherack.com
    twitter: HauteOffTheRack
  krystal:
    name: Krystal Bennett
    display_name: Krystal
    web: http://apinchoflovely.com
    twitter: KrystalBennett
prose:
  metadata:
    _posts:
      - name: "author"
        field:
          element: select
          label: "Author"
          options:
            - name: "Jennifer"
              value: "jennifer"
            - name: "Krystal"
              value: "krystal"
      - name: "layout"
        field:
          element: hidden
          value: "post"
      - name: "title"
        field:
          element: text
          label: "Title"
          type: text
      - name: "date"
        field:
          element: text
          label: "Date"
          placeholder: "YYYY-MM-DD HH:MM"
          type: text